name: stroll
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  pixel_perfect: ^1.1.3
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
  
  fonts:
    - family: Proxima_Nova
      fonts:
        - asset: fonts/Proxima-Nova-Regular.ttf
          weight: 400


